#
# This is set up information for the Amplicon Metagenomics Workflow,
# implemented in Snakemake. Set the parameters below, save the file and 
# run snakemake.
# Note that lines beginning with # are comments, i.e. they are ignored.
#
# Author: Oksana Korol
# Date: 16.06.2016
#

# Name (path) of the directory where snakemake will be executed; i.e. all other
# directories and files in this workflow will be relative to this directory
# You can change this parameter when initiating workflow execution like this:
### snakemake --config workdir="/path/to/some_other_directory"
workdir: "data"

# Where the initial input to the workflow will be located. Note that this directory
# is relative to the workdir above (i.e. the path would be <workdir>/<input_files_dir>)
# input_files_dir: "input_data" - does not work in input

# Input files to the workflow
# Below 2 files are from Qiime tutorial
#initial_input_forward: "input_ENV0047_S21_R1_001.fastq.gz"
#initial_input_reverse: "input_ENV0047_S21_R2_001.fastq.gz"

# Below 2 files are fake meta genomes from Jackson. Composition is:
#  ESL = 600000 Ecoli + 300000 Salmonella + 100000 Listeria reads
initial_input_forward: "ESL_R1_001.fastq.gz"
initial_input_reverse: "ESL_R2_001.fastq.gz"

 
# Number of threads to be used for execution of every tool in this workflow
threads: 1

# Trimmomatic parameters
trimmomatic:
    HEADCROP: "15" 
    SLIDINGWINDOW: "4:20" 
    MINLEN: "36"
    
    #LEADING: "25"
    #TRAILING: "25"
    #SLIDINGWINDOW: "1:25"
    #MINLEN: "100"

    #LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
   
pick_otus:
    s: "0.97"

assign_taxonomy:
    c: "0.70"
